version: '3'

services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: adsrental
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./dbdata1:/var/lib/mysql
    ports:
      - "13306:3306"
  php:
    build: php
    volumes:
      - ./php/cert/:/var/www/html/cert/
      - ./php/app/:/var/www/html/app/
      - ./php/log/:/var/www/html/log/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
    links:
      - db:db
  web:
    build: .
    command: /app/scripts/server.sh
    environment:
      ENV: dev
    ports:
      - "8007:8007"
    depends_on:
      - db
