version: '3'

services:
  db:
    image: mysql
    command: 'mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=300'
    environment:
      MYSQL_DATABASE: adsrental
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./dbdata1:/var/lib/mysql
    ports:
      - "23306:3306"
  web:
    build: .
    command: /app/scripts/runserver.sh
    privileged: true
    environment:
      ENV: local
      WERKZEUG_DEBUG_PIN: 'off'
      HTTPS: 'on'
      wsgi.url_scheme: 'https'
      UWSGI_INI: /app/config/nginx/uwsgi_debug.ini
    volumes:
      - ./cert/:/app/cert/
      - ./config/:/app/config/
      - ./static/:/app/static/
      - ./adsrental/:/app/adsrental/
      - ./scripts/:/app/scripts/
      - ./log/:/app/log/
      - ./app_log/:/app/app_log/
      - ./media/:/app/media/
    ports:
      - "8080:80"
      - "7443:443"
    depends_on:
      - db
    links:
      - db:db
      - redis:redis
  redis:
    restart: always
    image: redis:latest
    expose:
      - "6379"
  rdpclient:
    build: rdpclient
    command: ./run.sh
    volumes:
      - ./rdpclient/index-debug.html:/app/FreeRDP-WebConnect/wsgate/webroot/index-debug.html
    ports:
      - "9999:8000"
