version: '3'

services:
  db:
    restart: on-failure
    image: mysql
    command: 'mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=10000'
    environment:
      MYSQL_DATABASE: adsrental
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./dbdata1:/var/lib/mysql
    ports:
      - "13306:3306"
  web:
    restart: on-failure
    build: .
    command: /app/scripts/server.sh
    privileged: true
    environment:
      ENV: prod
      HTTPS: 'on'
      wsgi.url_scheme: 'https'
    volumes:
      - ./cert/:/app/cert/
      - ./config/:/app/config/
      - ./static/:/app/static/
      - ./adsrental/:/app/adsrental/
      - ./scripts/:/app/scripts/
      - /mnt/volume-nyc3-01/log/:/app/log/
      - /mnt/volume-nyc3-01/app_log/:/app/app_log/
      - /mnt/volume-nyc3-01/media/:/app/media/
    depends_on:
      - db
    links:
      - db:db
      - redis:redis
    ports:
      - "80:80"
      - "443:443"
  redis:
    restart: always
    image: redis:latest
    expose:
      - "6379"
