version: '3'

services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: adsrental
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./dbdata1:/var/lib/mysql
    ports:
      - "13306:3306"
  web:
    build: .
    command: /app/scripts/server.sh
    environment:
      ENV: dev
    ports:
      - "80:8007"
      - "8007:8007"
