env:
  browser: true
  es6: true
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  no-console:
    - warn
  no-unused-vars:
    - off
globals:
  browser: true
  extensionid: true
  sessionData: true
  experiment: true
